"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Check, ExternalLink, KeyRound, MessageCircle, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { createTelegramLink, createWheelhouseConnection, getTelegramStatus, getWheelhouseConnections, QUERY_KEYS } from "@/lib/api";
import { useOnboardingStore } from "@/store/onboarding";

export function OnboardingModal() {
  const queryClient=useQueryClient();const[step,setStep]=useState<1|2>(1);const[name,setName]=useState("Primary Wheelhouse account");const[credential,setCredential]=useState("");
  const organizationId=typeof window==="undefined"?"":window.localStorage.getItem("kivora.organizationId")||"current";
  const {manuallyOpen,dismissedOrganizations,dismiss}=useOnboardingStore();
  const connections=useQuery({queryKey:QUERY_KEYS.wheelhouseConnections,queryFn:getWheelhouseConnections});
  const telegram=useQuery({queryKey:QUERY_KEYS.telegramStatus,queryFn:getTelegramStatus});
  const wheelhouseConnected=Boolean(connections.data?.some((item)=>item.status!=="revoked"));const mobileConnected=Boolean(telegram.data?.connected);
  const needsSetup=!wheelhouseConnected||!mobileConnected;const automatic=!dismissedOrganizations.includes(organizationId)&&needsSetup;const open=(automatic||manuallyOpen)&&!connections.isLoading&&!telegram.isLoading;
  const connect=useMutation({mutationFn:()=>createWheelhouseConnection({displayName:name.trim(),credential:credential.trim()}),onSuccess:()=>{setCredential("");queryClient.invalidateQueries({queryKey:QUERY_KEYS.wheelhouseConnections});setStep(2);toast.success("Wheelhouse connected",{description:"Your first live portfolio synchronization is complete."});},onError:(error)=>toast.error(error instanceof Error?error.message:"Wheelhouse could not be connected")});
  const link=useMutation({mutationFn:createTelegramLink,onSuccess:(result)=>{window.open(result.url,"_blank","noopener,noreferrer");toast.success("Mobile companion opened",{description:"Tap Start in Telegram, then return here when linking is complete."});},onError:(error)=>toast.error(error instanceof Error?error.message:"Mobile companion could not be opened")});
  const progress=useMemo(()=>Number(wheelhouseConnected)+Number(mobileConnected),[wheelhouseConnected,mobileConnected]);
  return <AnimatePresence>{open&&<><motion.button aria-label="Close setup guide" className="fixed inset-0 z-[70] bg-black/75 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>dismiss(organizationId)}/><div className="pointer-events-none fixed inset-0 z-[71] flex items-end justify-center p-3 sm:items-center sm:p-4"><motion.section role="dialog" aria-modal="true" aria-labelledby="onboarding-title" initial={{opacity:0,y:24,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:16,scale:.98}} transition={{duration:.25}} className="pointer-events-auto max-h-[calc(100dvh-1.5rem)] w-full max-w-2xl overflow-y-auto rounded-3xl border border-white/10 bg-[#0f1012] shadow-2xl">
    <div className="border-b border-white/[0.06] p-5 sm:p-8"><div className="flex items-start gap-3 sm:gap-4"><div className="min-w-0 flex-1"><div className="eyebrow">Welcome to Kivora</div><h2 id="onboarding-title" className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">Let&apos;s connect your revenue workspace.</h2><p className="mt-2 max-w-xl text-xs leading-5 text-slate-400 sm:text-sm sm:leading-6">Two quick connections unlock live portfolio monitoring and mobile decisions. You can change either one later in Settings.</p></div><button onClick={()=>dismiss(organizationId)} className="shrink-0 rounded-xl border border-border p-2 text-slate-400 hover:text-foreground"><X size={16}/></button></div><div className="mt-5 flex items-center gap-3 sm:mt-6"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/[0.06]"><motion.div className="h-full rounded-full bg-accent" animate={{width:`${progress/2*100}%`}}/></div><span className="font-mono text-[10px] text-slate-500">{progress}/2 connected</span></div></div>
    <div className="p-5 sm:p-8">{step===1&&!wheelhouseConnected?<div><SetupTitle icon={<KeyRound size={19}/>} number="01" title="Connect Wheelhouse" description="Kivora validates the key live, encrypts it, and imports only your organization&apos;s listings."/><div className="mt-6 grid gap-3 sm:grid-cols-2"><label className="text-[10px] text-slate-500">Connection name<input value={name} onChange={(event)=>setName(event.target.value)} className="mt-1.5 w-full rounded-xl border border-border bg-elevated p-3 text-xs text-foreground"/></label><label className="text-[10px] text-slate-500">Wheelhouse API key<input type="password" autoComplete="off" value={credential} onChange={(event)=>setCredential(event.target.value)} placeholder="Paste your live API key" className="mt-1.5 w-full rounded-xl border border-border bg-elevated p-3 text-xs text-foreground"/></label></div><button disabled={connect.isPending||name.trim().length<2||credential.trim().length<8} onClick={()=>connect.mutate()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-accent px-5 py-3 text-xs font-bold text-white disabled:opacity-40 sm:w-auto">{connect.isPending?"Connecting your live portfolio…":"Connect Wheelhouse"}<ArrowRight size={14}/></button></div>:<div><SetupTitle icon={<MessageCircle size={19}/>} number="02" title="Connect your mobile companion" description="Receive morning briefings, ask portfolio questions, and review signed actions from Telegram."/>{mobileConnected?<div className="mt-6 flex items-center gap-3 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300"><Check size={18}/> Your mobile companion is connected.</div>:<div className="mt-6 rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4 sm:p-5"><p className="text-xs leading-6 text-slate-400">We&apos;ll open Telegram. Tap <strong className="text-foreground">Start</strong>, follow the secure link, then return to Kivora.</p><button disabled={link.isPending} onClick={()=>link.mutate()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-accent px-5 py-3 text-xs font-bold text-white disabled:opacity-40 sm:w-auto"><ExternalLink size={14}/>{link.isPending?"Opening companion…":"Open mobile companion"}</button></div>}<div className="mt-6 flex flex-col gap-3 min-[390px]:flex-row min-[390px]:flex-wrap">{!wheelhouseConnected&&<button onClick={()=>setStep(1)} className="rounded-xl border border-border px-4 py-2.5 text-xs">Back to Wheelhouse</button>}<button onClick={()=>dismiss(organizationId)} className="rounded-xl border border-border px-4 py-2.5 text-xs font-semibold">{mobileConnected&&wheelhouseConnected?"Enter my workspace":"Finish later"}</button></div></div>}</div>
  </motion.section></div></>}</AnimatePresence>;
}

function SetupTitle({icon,number,title,description}:{icon:React.ReactNode;number:string;title:string;description:string}){return <div className="flex gap-4"><span className="grid h-11 w-11 flex-none place-items-center rounded-2xl border border-accent/20 bg-accent/10 text-accent">{icon}</span><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-accent">Step {number}</div><h3 className="mt-1 text-base font-semibold">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-400">{description}</p></div></div>}
