"use client";
import { getBriefs, getIncidents, getOpportunities, getPortfolio, previewIncident, sendBrief, underwriteProperty } from "@/lib/api";
import { useMutation, useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { AlertTriangle, Building2, Copy, House, Search, Send, ShieldCheck, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export type WorkspaceView = "Overview" | "Incidents" | "Portfolio" | "Opportunities" | "Owner briefs" | "Underwrite";
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value || 0);
function Header({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="mb-7"><div className="text-[10px] font-bold uppercase tracking-[.14em] text-[#1b6b4a]">{eyebrow}</div><h2 className="display mt-2 text-3xl font-bold">{title}</h2><p className="mt-2 text-[12px] text-[#748079]">{copy}</p></div>; }
function Loading() { return <div className="card rounded-2xl p-8 text-center text-sm">Loading live data…</div>; }
function Failed({ error }: { error: unknown }) { return <div className="card rounded-2xl border border-red-200 p-8 text-center text-sm text-red-700">Live data unavailable: {error instanceof Error ? error.message : "request failed"}</div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="p-8 text-center text-sm text-[#748079]">{children}</div>; }

export function ProductView({ view, onIncident }: { view: Exclude<WorkspaceView, "Overview">; onIncident: () => void }) { return <motion.div key={view} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-[1440px] p-4 sm:p-7">{view === "Incidents" && <Incidents onOpen={onIncident} />}{view === "Portfolio" && <Portfolio />}{view === "Opportunities" && <Opportunities />}{view === "Owner briefs" && <Briefs />}{view === "Underwrite" && <Underwrite />}</motion.div>; }

function Incidents({ onOpen }: { onOpen: () => void }) { const query = useQuery({ queryKey: ["incidents"], queryFn: getIncidents }); if (query.isLoading) return <Loading />; if (query.error) return <Failed error={query.error} />; const items = query.data ?? []; return <><Header eyebrow="Revenue protection" title="Incidents" copy="Live pricing risks ranked by verified financial exposure." /><section className="card overflow-hidden rounded-2xl">{items.length === 0 ? <Empty>No open incidents in the latest Wheelhouse scan.</Empty> : items.map((item: any) => <button key={item.id} onClick={onOpen} className="flex w-full items-center gap-4 border-b p-5 text-left"><AlertTriangle className="text-[#9e412e]" /><span className="flex-1"><b className="block text-sm">{item.title}</b><small>{item.listing} · {new Date(item.detectedAt).toLocaleString()}</small></span><b className="text-[#9e412e]">{money(item.revenueAtRisk)}</b></button>)}</section></>; }

function Portfolio() { const [search, setSearch] = useState(""); const query = useQuery({ queryKey: ["portfolio"], queryFn: getPortfolio }); const rows = useMemo(() => (query.data?.listings ?? []).filter((item: any) => `${item.nickname || item.title || item.id} ${item.location?.address || ""}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]); if (query.isLoading) return <Loading />; if (query.error) return <Failed error={query.error} />; return <><Header eyebrow={`${rows.length} live listings`} title="Portfolio" copy="Properties and current KPI snapshots from Wheelhouse." /><label className="mb-4 flex w-fit items-center gap-2 rounded-xl border bg-white px-3 py-2"><Search size={14} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search listings" className="outline-none" /></label><section className="card overflow-x-auto rounded-2xl">{rows.length === 0 ? <Empty>No connected listings returned by Wheelhouse.</Empty> : rows.map((item: any) => <div key={item.id} className="grid grid-cols-[1fr_repeat(4,.35fr)] items-center gap-3 border-b p-5 text-sm"><span className="flex items-center gap-3"><Building2 size={17} /><b>{item.nickname || item.title || item.id}</b></span><span>Health {item.metrics?.health ?? "—"}</span><span>{money(item.metrics?.adr)}</span><span>{item.metrics ? `${(item.metrics.occupancy * 100).toFixed(1)}%` : "—"}</span><b>{money(item.metrics?.revenue)}</b></div>)}</section></>; }

function Opportunities() { const query = useQuery({ queryKey: ["opportunities"], queryFn: getOpportunities }); const preview = useMutation({ mutationFn: previewIncident, onSuccess: (result) => toast.success(`Live preview: ${money(result.projectedRecovery)} projected recovery`), onError: (error) => toast.error(error instanceof Error ? error.message : "Preview failed") }); if (query.isLoading) return <Loading />; if (query.error) return <Failed error={query.error} />; return <><Header eyebrow="Revenue upside" title="Opportunities" copy="Actions derived only from live, detected incidents." /><div className="grid gap-3">{query.data?.length ? query.data.map((item: any) => <article key={item.id} className="card flex items-center gap-4 rounded-2xl p-5"><TrendingUp className="text-[#26704f]" /><div className="flex-1"><b>{item.property}</b><p className="text-sm text-[#748079]">{item.action} · {item.confidence}% confidence</p></div><b>+{money(item.impact)}</b><button onClick={() => preview.mutate(item.id)} className="rounded-xl bg-[#173f2e] px-4 py-3 text-xs font-bold text-white">Live preview</button></article>) : <section className="card rounded-2xl"><Empty>No live opportunities detected.</Empty></section>}</div></>; }

function Briefs() { const query = useQuery({ queryKey: ["briefs"], queryFn: getBriefs }); const [selected, setSelected] = useState(0); const send = useMutation({ mutationFn: sendBrief, onSuccess: () => { toast.success("Brief delivered to Telegram"); query.refetch(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Delivery failed") }); if (query.isLoading) return <Loading />; if (query.error) return <Failed error={query.error} />; const items = query.data ?? []; const current = items[selected]; return <><Header eyebrow="Owner success" title="Owner briefs" copy="Groq-generated updates created after verified live actions." /><div className="grid gap-4 lg:grid-cols-2"><section className="card rounded-2xl">{items.length ? items.map((item: any, index: number) => <button key={item._id} onClick={() => setSelected(index)} className="block w-full border-b p-4 text-left"><b>{item.owner || item.listingId}</b><small className="block">{item.subject} · {item.status}</small></button>) : <Empty>No briefs have been generated.</Empty>}</section>{current && <section className="card rounded-2xl p-6"><h3 className="font-bold">{current.subject}</h3><p className="my-5 whitespace-pre-wrap text-sm leading-7">{current.body}</p><div className="flex justify-end gap-2"><button onClick={() => navigator.clipboard?.writeText(current.body)} className="rounded-xl border p-3"><Copy size={15} /></button><button disabled={send.isPending || current.status === "sent"} onClick={() => send.mutate(current._id)} className="flex items-center gap-2 rounded-xl bg-[#173f2e] px-4 py-3 text-xs font-bold text-white"><Send size={14} /> Deliver via Telegram</button></div></section>}</div></>; }

function Underwrite() { const [address, setAddress] = useState(""); const [marketId, setMarketId] = useState(""); const [cost, setCost] = useState(""); const [expenses, setExpenses] = useState(""); const mutation = useMutation({ mutationFn: underwriteProperty, onError: (error) => toast.error(error instanceof Error ? error.message : "Underwriting failed") }); const valid = address && Number(marketId) > 0 && Number(cost) > 0 && Number(expenses) >= 0; return <><Header eyebrow="Live market underwriting" title="Underwrite a deal" copy="Uses a real Wheelhouse market report and your explicit investment assumptions." /><section className="card rounded-3xl p-7"><div className="mb-5 flex items-center gap-2 font-bold"><House /> Acquisition inputs</div><div className="grid gap-3 md:grid-cols-4"><input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Property address" className="rounded-xl border p-3" /><input value={marketId} onChange={(event) => setMarketId(event.target.value)} placeholder="Wheelhouse market ID" className="rounded-xl border p-3" /><input value={cost} onChange={(event) => setCost(event.target.value)} placeholder="Acquisition cost" className="rounded-xl border p-3" /><input value={expenses} onChange={(event) => setExpenses(event.target.value)} placeholder="Annual expenses" className="rounded-xl border p-3" /></div><button disabled={!valid || mutation.isPending} onClick={() => mutation.mutate({ address, marketId: Number(marketId), acquisitionCost: Number(cost), annualExpenses: Number(expenses) })} className="mt-4 rounded-xl bg-[#d8f45b] px-6 py-3 font-bold disabled:opacity-40">Analyze live market</button>{mutation.data && <div className="mt-7 grid gap-3 md:grid-cols-4">{[["Annual revenue", money(mutation.data.annualRevenue)], ["NOI", money(mutation.data.netOperatingIncome)], ["Occupancy", `${mutation.data.occupancy}%`], ["ROI", `${mutation.data.cashOnCashRoi}%`]].map(([label, value]) => <div key={label} className="rounded-xl border p-4"><small>{label}</small><div className="mt-2 text-xl font-bold">{value}</div></div>)}<div className="md:col-span-4 flex gap-2 rounded-xl bg-[#edf5ef] p-4"><ShieldCheck /> Source: {mutation.data.source}</div></div>}</section></>; }
