import {BadRequestException,ForbiddenException,Injectable,NotFoundException,ServiceUnavailableException} from "@nestjs/common";
import {ConfigService} from "@nestjs/config";import {InjectModel} from "@nestjs/mongoose";import {createCipheriv,createDecipheriv,randomBytes} from "crypto";import {Model,Types} from "mongoose";import {firstValueFrom} from "rxjs";import {HttpService} from "@nestjs/axios";
import {AuthenticatedUser} from "../../auth/guards/privy-auth.guard";import {OrganizationIntegrationConfig,NotificationPreference} from "../schemas/organization-integration.schema";

@Injectable()
export class OrganizationIntegrationService{
 private readonly key?:Buffer;private readonly platform:Record<string,string|undefined>;
 constructor(config:ConfigService,private readonly http:HttpService,@InjectModel(OrganizationIntegrationConfig.name)private readonly configs:Model<OrganizationIntegrationConfig>,@InjectModel(NotificationPreference.name)private readonly preferences:Model<NotificationPreference>){const raw=config.get<string>("WHEELHOUSE_CREDENTIAL_ENCRYPTION_KEY");if(raw&&/^[a-fA-F0-9]{64}$/.test(raw))this.key=Buffer.from(raw,"hex");this.platform={ticketmaster:config.get("TICKETMASTER_API_KEY"),openweather:config.get("OPENWEATHER_API_KEY")};}
 async list(actor:AuthenticatedUser){const rows:any[]=await this.configs.find({organizationId:new Types.ObjectId(actor.organizationId)}).lean();return ["ticketmaster","openweather"].map(provider=>{const row=rows.find(x=>x.provider===provider);return{provider,enabled:row?.enabled||false,credentialMode:row?.credentialMode||"platform",credentialConfigured:Boolean(row?.credentialMode==="organization"?row?.credentialUpdatedAt:this.platform[provider]),settings:row?.settings||this.defaults(provider),status:row?.status||"disabled",lastSuccessfulCollection:row?.lastSuccessfulCollection,lastFailure:row?.lastFailure,lastError:row?.lastError};});}
 async update(actor:AuthenticatedUser,provider:string,input:any){this.manager(actor);this.provider(provider);const organizationId=new Types.ObjectId(actor.organizationId);const current:any=await this.configs.findOne({organizationId,provider}).select("+encryptedCredential").lean();let encrypted=current?.encryptedCredential;if(input.credential){if(!this.key)throw new ServiceUnavailableException("Credential encryption is not configured");encrypted=this.encrypt(input.credential);}if(input.credentialMode==="organization"&&!encrypted)throw new BadRequestException("An organization credential is required");const row:any=await this.configs.findOneAndUpdate({organizationId,provider},{$set:{organizationId,provider,enabled:Boolean(input.enabled),credentialMode:input.credentialMode||"platform",settings:{...this.defaults(provider),...(input.settings||{})},status:input.enabled?"configured":"disabled",...(input.credential?{encryptedCredential:encrypted,credentialUpdatedAt:new Date()}:{})}}, {upsert:true,returnDocument:"after"}).lean();return{provider:row.provider,enabled:row.enabled,credentialMode:row.credentialMode,credentialConfigured:Boolean(input.credential||row.credentialUpdatedAt||this.platform[provider]),settings:row.settings,status:row.status};}
 async revoke(actor:AuthenticatedUser,provider:string){this.manager(actor);const row=await this.configs.findOneAndUpdate({organizationId:new Types.ObjectId(actor.organizationId),provider},{$set:{enabled:false,status:"disabled"},$unset:{encryptedCredential:1,credentialUpdatedAt:1}},{returnDocument:"after"}).lean();if(!row)throw new NotFoundException("Integration configuration not found");return{provider,status:"disabled",credentialConfigured:false};}
 async credential(organizationId:string,provider:string){this.provider(provider);const row:any=await this.configs.findOne({organizationId:new Types.ObjectId(organizationId),provider,enabled:true}).select("+encryptedCredential").lean();if(!row)return null;const credential=row.credentialMode==="organization"?(row.encryptedCredential?this.decrypt(row.encryptedCredential):undefined):this.platform[provider];return credential?{credential,config:row}:null;}
 async providerSettings(organizationId:string,provider:string){const row:any=await this.configs.findOne({organizationId:new Types.ObjectId(organizationId),provider,enabled:true}).lean();return row?.settings||null;}
 async test(actor:AuthenticatedUser,provider:string){const selected=await this.credential(actor.organizationId,provider);if(!selected)throw new ServiceUnavailableException("Integration is disabled or has no credential");try{if(provider==="ticketmaster")await firstValueFrom(this.http.get("https://app.ticketmaster.com/discovery/v2/events.json",{params:{apikey:selected.credential,size:1}}));else await firstValueFrom(this.http.get("https://api.openweathermap.org/data/2.5/forecast",{params:{lat:0,lon:0,appid:selected.credential,units:"metric",cnt:1}}));await this.configs.updateOne({_id:selected.config._id},{$set:{status:"connected",lastSuccessfulCollection:new Date()},$unset:{lastError:1,lastFailure:1}});return{provider,connected:true,mode:selected.config.credentialMode};}catch(error){await this.configs.updateOne({_id:selected.config._id},{$set:{status:"degraded",lastFailure:new Date(),lastError:this.error(error)}});throw new ServiceUnavailableException(`${provider} credential validation failed`);}}
 async record(organizationId:string,provider:string,error?:unknown){await this.configs.updateOne({organizationId:new Types.ObjectId(organizationId),provider},error?{$set:{status:"degraded",lastFailure:new Date(),lastError:this.error(error)}}:{$set:{status:"connected",lastSuccessfulCollection:new Date()},$unset:{lastError:1,lastFailure:1}});}
 async getPreferences(actor:AuthenticatedUser){const organizationId=new Types.ObjectId(actor.organizationId);const [org,user]=await Promise.all([this.preferences.findOne({organizationId,scope:"organization"}).lean(),this.preferences.findOne({organizationId,scope:"user",userId:new Types.ObjectId(actor.sub)}).lean()]);return{organization:org||this.preferenceDefaults(actor.organizationId),user:user||null,effective:this.merge(org as any,user as any)};}
 async savePreferences(actor:AuthenticatedUser,scope:string,input:any){if(["organization","portfolio"].includes(scope))this.manager(actor);if(!["organization","user","portfolio"].includes(scope))throw new BadRequestException("Unsupported preference scope");const organizationId=new Types.ObjectId(actor.organizationId);const filter:any={organizationId,scope};if(scope==="user")filter.userId=new Types.ObjectId(actor.sub);if(scope==="portfolio"){if(!Types.ObjectId.isValid(input.portfolioId))throw new BadRequestException("A valid portfolio is required");filter.portfolioId=new Types.ObjectId(input.portfolioId);}const row=await this.preferences.findOneAndUpdate(filter,{$set:{...filter,channels:input.channels||{},categories:input.categories||{},minimumFinancialImpact:Number(input.minimumFinancialImpact||0),severities:input.severities||[],assignedUserOnly:Boolean(input.assignedUserOnly),quietHoursStart:input.quietHoursStart,quietHoursEnd:input.quietHoursEnd,timezone:input.timezone||"UTC",deliveryMode:input.deliveryMode||"immediate"}},{upsert:true,returnDocument:"after"}).lean();return row;}
 async permits(organizationId:string,userId:string|undefined,category:string,channel:string,impact=0,severity?:string,context:{portfolioId?:string;assignedUserId?:string}={}){const org=new Types.ObjectId(organizationId);const [base,portfolio,override]=await Promise.all([this.preferences.findOne({organizationId:org,scope:"organization"}).lean(),context.portfolioId?this.preferences.findOne({organizationId:org,scope:"portfolio",portfolioId:new Types.ObjectId(context.portfolioId)}).lean():null,userId?this.preferences.findOne({organizationId:org,scope:"user",userId:new Types.ObjectId(userId)}).lean():null]);const p=this.merge(this.merge(base as any,portfolio as any),override as any);if(p.channels?.[channel]===false||p.categories?.[category]===false||impact<Number(p.minimumFinancialImpact||0))return false;if(severity&&p.severities?.length&&!p.severities.includes(severity))return false;if(p.assignedUserOnly&&(!userId||context.assignedUserId!==userId))return false;if(this.quiet(p))return false;if(p.deliveryMode==="daily_digest"&&!['daily_briefing','end_of_day_summary'].includes(category))return false;return true;}
 private merge(base:any,override:any){return{...this.preferenceDefaults(""),...(base||{}),...(override||{}),channels:{...this.preferenceDefaults("").channels,...(base?.channels||{}),...(override?.channels||{})},categories:{...this.preferenceDefaults("").categories,...(base?.categories||{}),...(override?.categories||{})}};}
 private preferenceDefaults(_org:string){return{channels:{in_app:true,telegram:true,email:false},categories:{critical_incident:true,high_incident:true,opportunity:true,event_opportunity:true,weather_opportunity:true,recommendation_awaiting_approval:true,scheduled_action_approaching:true,scheduled_action_executed:true,action_failed:true,verification_failed:true,partial_action:true,outcome_available:true,report_ready:true,daily_briefing:true,end_of_day_summary:true,integration_degraded:true,synchronization_failure:true},minimumFinancialImpact:0,severities:[],timezone:"UTC",deliveryMode:"immediate"};}
 private defaults(provider:string){return provider==="ticketmaster"?{eventSearchRadiusMiles:30,eventCategories:["Music","Sports","Arts & Theatre"],minimumEventRelevance:65,opportunityThreshold:100}:{weatherAlertThreshold:0.65,forecastHorizonDays:5,enabledPropertyProfiles:["beachfront","downtown","business_district","resort","outdoor_recreation","shopping_district","indoor_attraction_area","ski_destination","coastal"],opportunityThreshold:0};}
 private quiet(p:any){if(!p.quietHoursStart||!p.quietHoursEnd)return false;try{const parts=new Intl.DateTimeFormat("en-GB",{timeZone:p.timezone||"UTC",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date());const now=Number(parts.find(x=>x.type==="hour")?.value)*60+Number(parts.find(x=>x.type==="minute")?.value);const parse=(v:string)=>{const[h,m]=v.split(":").map(Number);return h*60+m;};const start=parse(p.quietHoursStart),end=parse(p.quietHoursEnd);return start<=end?now>=start&&now<end:now>=start||now<end;}catch{return false;}}private provider(p:string){if(!["ticketmaster","openweather"].includes(p))throw new BadRequestException("Unsupported provider");}private manager(a:AuthenticatedUser){if(!["owner","administrator"].includes(a.organizationRole))throw new ForbiddenException("Organization administrator permission is required");}private encrypt(v:string){const iv=randomBytes(12),c=createCipheriv("aes-256-gcm",this.key!,iv),body=Buffer.concat([c.update(v,"utf8"),c.final()]);return`v1.${iv.toString("base64url")}.${c.getAuthTag().toString("base64url")}.${body.toString("base64url")}`;}private decrypt(v:string){if(!this.key)throw new ServiceUnavailableException("Credential encryption is unavailable");const[,i,t,b]=v.split("."),d=createDecipheriv("aes-256-gcm",this.key,Buffer.from(i,"base64url"));d.setAuthTag(Buffer.from(t,"base64url"));return Buffer.concat([d.update(Buffer.from(b,"base64url")),d.final()]).toString("utf8");}private error(e:unknown){return e instanceof Error?e.message.slice(0,300):"Integration request failed";}
}
