"use client";

import { usePrivy } from "@privy-io/react-auth";
import { AnimatePresence, motion, useScroll, useTransform } from "framer-motion";
import { Activity, ArrowRight, Bot, BrainCircuit, Check, Menu, Radar, ShieldCheck, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

const configured=Boolean(process.env.NEXT_PUBLIC_PRIVY_APP_ID);
const nav=[{label:"Platform",href:"#platform"},{label:"Workflow",href:"#workflow"},{label:"Telegram",href:"#telegram"}];

function PrivyLaunch({className=""}:{className?:string}){const {ready,authenticated,login}=usePrivy();const router=useRouter();return <button disabled={!ready} onClick={()=>authenticated?router.push("/dashboard"):login()} className={className}>{authenticated?"Open workspace":"Launch Kivora"}<ArrowRight size={15}/></button>}
function Launch({className=""}:{className?:string}){if(!configured)return <button onClick={()=>toast.error("Add NEXT_PUBLIC_PRIVY_APP_ID to frontend/.env.local")} className={className}>Configure Privy <ArrowRight size={15}/></button>;return <PrivyLaunch className={className}/>}

function Navbar(){const [scrolled,setScrolled]=useState(false),[open,setOpen]=useState(false);useEffect(()=>{const fn=()=>setScrolled(scrollY>50);addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);return <><header className="pointer-events-none fixed inset-x-0 top-0 z-50 flex justify-center px-4 pt-4 md:pt-6"><motion.nav initial={{y:-50,opacity:0}} animate={{y:0,opacity:1}} className={`pointer-events-auto relative flex w-full max-w-5xl items-center justify-between rounded-full border px-5 py-2.5 backdrop-blur-xl ${scrolled?"border-[#FF1301]/20 bg-surface/80 shadow-2xl":"border-white/6 bg-canvas/30"}`}><Link href="#top" className="flex items-center gap-2.5"><div className="relative h-8 w-8"><motion.div animate={{rotate:360}} transition={{repeat:Infinity,duration:10,ease:"linear"}} className="absolute inset-0 rounded-xl bg-gradient-to-tr from-accent to-accent-2"/><div className="absolute inset-px grid place-items-center rounded-[11px] bg-canvas font-mono text-sm font-black">K</div></div><span className="font-display text-lg font-bold">Kivora<span className="text-accent-2">.</span></span></Link><div className="hidden items-center gap-1 md:flex">{nav.map(n=><Link className="rounded-full px-4 py-2 text-sm font-medium text-slate-400 transition hover:bg-white/5 hover:text-white" href={n.href} key={n.href}>{n.label}</Link>)}</div><Launch className="hidden items-center gap-2 rounded-full bg-gradient-to-r from-accent to-accent-2 px-5 py-2.5 text-xs font-bold uppercase tracking-wider shadow-[0_15px_35px_-10px_rgba(255,19,1,.55)] md:flex"/><button aria-label="Toggle menu" onClick={()=>setOpen(v=>!v)} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-slate-400 md:hidden">{open?<X size={18}/>:<Menu size={18}/>}</button></motion.nav></header><AnimatePresence>{open&&<motion.div initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} className="fixed left-4 right-4 top-20 z-40 rounded-2xl border border-[#FF1301]/20 bg-surface/95 p-4 shadow-2xl backdrop-blur-xl">{nav.map(n=><Link onClick={()=>setOpen(false)} className="block rounded-xl px-4 py-3 text-sm font-semibold text-slate-400 hover:bg-white/5 hover:text-white" href={n.href} key={n.href}>{n.label}</Link>)}<Launch className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-accent to-accent-2 px-4 py-3 text-sm font-bold"/></motion.div>}</AnimatePresence></>}

const bars=Array.from({length:32},(_,i)=>22+Math.exp(-Math.pow((i/31-.5)*3.2,2))*68);
function Hero(){const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start start","end start"]});const y=useTransform(scrollYProgress,[0,1],[0,120]),opacity=useTransform(scrollYProgress,[0,.6],[1,0]);return <section id="top" ref={ref} className="relative flex min-h-screen items-center justify-center overflow-hidden"><div className="absolute inset-0 flex items-end gap-[2px] px-4 opacity-80 md:px-12" style={{maskImage:"linear-gradient(180deg,transparent,black 20%,black 80%,transparent)"}}>{bars.map((h,i)=><motion.div key={i} className="flex-1 rounded-t-sm bg-gradient-to-t from-accent/60 to-accent/5" animate={{height:[`${h}%`,`${Math.max(h*.55,6)}%`,`${Math.min(h*1.25,96)}%`,`${h}%`]}} transition={{duration:2+(i%5)*.2,delay:i*.05,repeat:Infinity,ease:"easeInOut"}}/>)}</div><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_28%,#0a0a0c_88%)]"/><motion.div style={{y,opacity}} className="relative z-10 flex max-w-5xl flex-col items-center px-4 text-center"><motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{delay:.25}} className="mb-7 flex items-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-4 py-2 font-mono text-[10px] uppercase tracking-[.24em] text-slate-400"><span className="live-dot h-1.5 w-1.5 rounded-full bg-accent"/> Autonomous revenue intelligence</motion.div><h1 className="font-display text-6xl font-black leading-[.92] tracking-[-.07em] sm:text-7xl md:text-9xl"><motion.span initial={{y:70,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.85,ease:[.16,1,.3,1]}} className="block">Revenue.</motion.span><motion.span initial={{y:70,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.85,delay:.12,ease:[.16,1,.3,1]}} className="text-gradient block">On watch.</motion.span></h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.7}} className="mt-8 max-w-2xl text-base font-light leading-relaxed text-slate-400 sm:text-lg">Kivora continuously watches your Wheelhouse portfolio, explains revenue leakage, and routes verified actions to the right operator—in the web workspace or Telegram.</motion.p><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.9}} className="mt-10 flex flex-col gap-4 sm:flex-row"><Launch className="flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-accent to-accent-2 px-9 py-4 text-sm font-bold shadow-[0_15px_35px_-10px_rgba(255,19,1,.55)] transition hover:-translate-y-1"/><Link href="#workflow" className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-9 py-4 text-sm font-semibold text-slate-300 transition hover:bg-white/[.08]">See the workflow <ArrowRight size={15}/></Link></motion.div></motion.div><div className="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 font-mono text-[9px] uppercase tracking-[.3em] text-faint">Scroll to inspect</div></section>}

const capabilities=[{n:"01",icon:Radar,title:"Detect",text:"Continuously compares live Wheelhouse listings, pricing preferences, KPIs, and market signals."},{n:"02",icon:BrainCircuit,title:"Diagnose",text:"Groq turns raw anomalies into concise causes, confidence scores, evidence, and operator-ready actions."},{n:"03",icon:ShieldCheck,title:"Act safely",text:"Every mutation is previewed first, requires an authenticated manager, and writes an audit trail."},{n:"04",icon:Bot,title:"Operate anywhere",text:"Signed Telegram account linking gives every user their own alerts, briefings, and approval controls."}];
function Platform(){return <section id="platform" className="relative border-t border-white/6 bg-canvas py-28"><div className="grid-pattern absolute inset-0 opacity-50"/><div className="relative mx-auto max-w-6xl px-4"><div className="mb-14 max-w-2xl"><div className="font-mono text-xs uppercase tracking-[.24em] text-accent">01 / Platform</div><h2 className="mt-4 font-display text-4xl font-black tracking-[-.05em] sm:text-6xl">A revenue control room that never clocks out.</h2></div><div className="grid gap-4 md:grid-cols-2">{capabilities.map(({n,icon:I,title,text},i)=><motion.article key={title} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} whileHover={{y:-5}} className="glass-card group relative overflow-hidden rounded-3xl p-7"><div className="absolute right-5 top-3 font-mono text-7xl font-black text-white/[.025]">{n}</div><div className="grid h-11 w-11 place-items-center rounded-xl border border-[#FF1301]/25 bg-[#FF1301]/10 text-accent"><I size={21}/></div><h3 className="mt-8 font-display text-2xl font-bold">{title}</h3><p className="mt-3 max-w-md text-sm font-light leading-7 text-slate-400">{text}</p></motion.article>)}</div></div></section>}

const logs=["Authenticated with Wheelhouse RM API","Fetched live portfolio and listing preferences","Anomaly found: dynamic pricing disabled","Groq diagnosis completed · 97% confidence","Manager approval required before mutation"];
function Workflow(){return <section id="workflow" className="relative overflow-hidden py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_40%,rgba(255,19,1,.1),transparent_35%)]"/><div className="relative mx-auto grid max-w-6xl items-center gap-14 px-4 lg:grid-cols-[.85fr_1.15fr]"><div><div className="font-mono text-xs uppercase tracking-[.24em] text-accent">02 / Workflow</div><h2 className="mt-4 font-display text-4xl font-black tracking-[-.05em] sm:text-6xl">Live inputs. Human control.</h2><p className="mt-6 text-sm font-light leading-7 text-slate-400">Kivora does not fabricate portfolio data or silently change pricing. If a live integration is unavailable, it says so. When action is possible, the operator sees the evidence and approves the exact change.</p><div className="mt-8 space-y-3">{["Non-mutating preview","Privy-authenticated approval","MongoDB audit history"].map(t=><div key={t} className="flex items-center gap-3 text-sm text-slate-300"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-500/10 text-emerald-400"><Check size={13}/></span>{t}</div>)}</div></div><motion.div initial={{opacity:0,x:30}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="overflow-hidden rounded-2xl border border-white/10 bg-[#08080a] shadow-[0_35px_100px_rgba(0,0,0,.75)]"><div className="flex items-center border-b border-white/8 px-4 py-3"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-accent"/><span className="h-2.5 w-2.5 rounded-full bg-accent-2"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-500"/></div><span className="mx-auto font-mono text-[9px] uppercase tracking-[.2em] text-slate-600">Kivora operations console</span></div><div className="min-h-[360px] p-5 font-mono text-[11px]"><div className="mb-5 flex items-center justify-between text-slate-500"><span>LIVE MONITOR</span><span className="flex items-center gap-2 text-emerald-400"><Activity size={12}/> NOMINAL</span></div>{logs.map((l,i)=><motion.div key={l} initial={{opacity:0,x:-8}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:.2+i*.18}} className="mb-4 grid grid-cols-[55px_1fr] gap-3"><span className="text-slate-700">12:0{i}:0{i}</span><span className={i===2?"text-accent-2":i===4?"text-accent":"text-slate-300"}><span className="mr-2 text-slate-600">›</span>{l}</span></motion.div>)}<div className="mt-7 rounded-xl border border-[#FF1301]/20 bg-[#FF1301]/5 p-4"><div className="text-[9px] uppercase tracking-[.2em] text-accent">Pending action</div><div className="mt-2 text-slate-300">Restore dynamic pricing after live preview</div><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/5"><motion.div initial={{width:0}} whileInView={{width:"76%"}} transition={{duration:1.2}} className="h-full bg-gradient-to-r from-accent to-accent-2"/></div></div></div></motion.div></div></section>}

function Telegram(){return <section id="telegram" className="border-y border-white/6 bg-surface py-28"><div className="mx-auto max-w-6xl px-4 text-center"><div className="font-mono text-xs uppercase tracking-[.24em] text-accent">03 / Telegram</div><h2 className="mx-auto mt-4 max-w-3xl font-display text-4xl font-black tracking-[-.05em] sm:text-6xl">One bot. Every user gets their own workspace.</h2><p className="mx-auto mt-6 max-w-2xl text-sm font-light leading-7 text-slate-400">Starting the bot creates a short-lived signed link. Privy proves who is connecting; Kivora then binds only that Telegram identity to only that MongoDB user.</p><div className="mx-auto mt-10 flex max-w-2xl flex-wrap justify-center gap-2">{["No global chat ID","One-time signed intents","Per-user delivery","Role-gated approvals"].map(t=><span key={t} className="rounded-full border border-white/10 bg-white/[.03] px-4 py-2 font-mono text-[10px] uppercase tracking-wider text-slate-400">{t}</span>)}</div></div></section>}

function Footer(){return <footer className="relative overflow-hidden bg-canvas"><div className="mx-auto max-w-6xl px-4 py-24 text-center"><div className="font-display text-6xl font-black tracking-[-.07em] sm:text-8xl">Protect the next <span className="text-gradient">booking.</span></div><p className="mx-auto mt-6 max-w-xl text-sm leading-7 text-slate-400">Connect your live revenue stack and put every meaningful anomaly in front of the right person.</p><Launch className="mx-auto mt-9 flex items-center gap-2 rounded-full bg-gradient-to-r from-accent to-accent-2 px-9 py-4 text-sm font-bold shadow-[0_15px_35px_-10px_rgba(255,19,1,.55)]"/></div><div className="border-t border-white/6 px-4 py-6"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-3 font-mono text-[10px] uppercase tracking-widest text-slate-600 sm:flex-row"><span>© {new Date().getFullYear()} Kivora</span><span>Wheelhouse · Groq · Privy · Telegram</span></div></div></footer>}

export function Landing(){return <main><Navbar/><Hero/><Platform/><Workflow/><Telegram/><Footer/></main>}
